### ISSUE TITLE
Disable module with a boolean

### ISSUE THREAD

**Issue by dfredell** [terraform-google-modules/terraform-google-bastion-host#33]
It would be nice to toggle the creation of this whole module with a bool variable, ex `create_bastion`  

This would be something similar to https://github.com/terraform-aws-modules/terraform-aws-eks/pull/588/files

Our use case is, we have one large set of terraforms with modules and we are using a separate terraform.tfvars for every environment and toggle features off and on in there.

**Comment by morgante** [comment]
Hopefully HashiCorp makes some progress on fixing this [in core](https://github.com/hashicorp/terraform/issues/17519) soon, but happy to accept a PR adding this.

**Comment by onetwopunch** [comment]
@dfredell we actually do have an option that may suit your needs. Take a look at `create_instance_from_template`. If set to false, only the instance template is created so that you can use it in your own MIG, but no instances are spun up. We use this for the Bastion Group module. Since no instances are created, your bill should not be affected. Then when you want to create an instance, simply turn it on. If the goal is to not create any resources at all, we would have to add a count on every resource to condtionally turn it off like the module you referenced.

**Comment by dfredell** [comment]
That is a good work around. It would also be nice if hashicorp would just add count to all terraform modules. 

We actually decided to terraform in IAP to one of our existing instances, so we didn't end up using this module.
